import { BusinessConfig } from "@/src/types/domain";

const haircutImage =
  "https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&w=900&q=80";
const beardImage =
  "https://images.unsplash.com/photo-1621605815971-fbc98d665033?auto=format&fit=crop&w=900&q=80";

export const luxuryCutConfig: BusinessConfig = {
  id: "tenant-luxury-cut-02",
  slug: "luxury-cut",
  name: "Luxury Cut",
  headline: "دقت کلاسیک، استایل امروزی",
  description:
    "یک تجربه آرام و دقیق برای اصلاح مو و ریش، با زمان‌بندی روشن و خدمات شخصی‌سازی‌شده.",
  logo: haircutImage,
  coverImage: haircutImage,
  phone: "+1 212 555 0188",
  phoneDisplay: "+1 212 555 0188",
  address: "18 Mercer Street, New York",
  city: "New York",
  locale: "en-US",
  timezone: "America/New_York",
  currency: "USD",
  currencySymbol: "$",
  rating: 4.8,
  reviewsCount: 126,
  theme: { palette: "sky", fontFamily: "Inter, sans-serif" },
  localization: {
    locale: "en-US",
    timezone: "America/New_York",
    currency: "USD",
    currencySymbol: "$",
    direction: "ltr",
    phoneCountry: "US",
  },
  content: {
    hero: {
      eyebrow: "Modern barbershop",
      ctaLabel: "Choose a service",
      availabilityLabel: "Appointments available today",
    },
    labels: {
      servicesTitle: "Choose your service",
      servicesDescription:
        "Select a cut or grooming service to see available times.",
      staffTitle: "Choose your barber",
      staffDescription:
        "Pick a barber or let the shop match you with the first available chair.",
      historyDescription: "Your appointments at Luxury Cut",
    },
    policies: {
      payment: "Pay at the shop after your appointment.",
      cancellation:
        "Changes are welcome up to 12 hours before your appointment.",
      arrival: "Please arrive five minutes early.",
      privacy: "Your details are used only to manage this appointment.",
    },
    contact: { infoTitle: "Shop details", socialLabel: "Visit our Instagram" },
  },
  booking: {
    requireStaffSelection: true,
    allowCustomerNotes: true,
    allowCancellation: true,
    allowRescheduling: true,
    minNoticeHours: 12,
    maxAdvanceDays: 21,
    allowAnyStaff: true,
    flow: {
      showServiceSelection: true,
      showStaffSelection: true,
      showDateSelection: true,
      showTimeSelection: true,
      showCustomerDetails: true,
      showReview: true,
      allowServiceSearch: false,
      allowCategoryNavigation: true,
    },
  },
  categories: [
    { id: "cuts", name: "Haircuts", slug: "cuts" },
    { id: "grooming", name: "Grooming", slug: "grooming" },
  ],
  services: [
    {
      id: "cut-classic",
      slug: "classic-haircut",
      categoryId: "cuts",
      name: "Classic Haircut",
      description: "A precise cut finished with a hot towel neck clean-up.",
      durationMinutes: 45,
      price: 45,
      image: haircutImage,
      active: true,
      staffIds: ["barber-maya", "barber-jordan"],
      isFeatured: true,
    },
    {
      id: "cut-fade",
      slug: "skin-fade",
      categoryId: "cuts",
      name: "Skin Fade",
      description: "A clean fade shaped to your face and preferred length.",
      durationMinutes: 60,
      price: 60,
      image: haircutImage,
      active: true,
      staffIds: ["barber-jordan"],
    },
    {
      id: "beard-trim",
      slug: "beard-trim",
      categoryId: "grooming",
      name: "Beard Trim",
      description: "Shape, line-up, and finish for a polished beard.",
      durationMinutes: 30,
      price: 30,
      image: beardImage,
      active: true,
      staffIds: ["barber-maya"],
    },
    {
      id: "hair-beard",
      slug: "hair-and-beard",
      categoryId: "grooming",
      name: "Hair + Beard",
      description: "The complete haircut and beard grooming appointment.",
      durationMinutes: 90,
      price: 85,
      image: beardImage,
      active: true,
      staffIds: ["barber-maya", "barber-jordan"],
    },
  ],
  staff: [
    {
      id: "barber-maya",
      name: "Maya Brooks",
      role: "Senior Barber",
      avatar: haircutImage,
      bio: "Known for precise scissor work and natural finishes.",
      rating: 4.9,
      experienceYears: 8,
      isAvailable: true,
      active: true,
      serviceIds: ["cut-classic", "beard-trim", "hair-beard"],
    },
    {
      id: "barber-jordan",
      name: "Jordan Lee",
      role: "Fade Specialist",
      avatar: beardImage,
      bio: "Specializes in fades, texture, and modern short styles.",
      rating: 4.8,
      experienceYears: 6,
      isAvailable: true,
      active: true,
      serviceIds: ["cut-classic", "cut-fade", "hair-beard"],
    },
  ],
  locations: [
    {
      id: "luxury-cut-nyc",
      name: "Mercer Street Shop",
      address: "18 Mercer Street, New York",
      city: "New York",
      phone: "+1 212 555 0188",
    },
  ],
  workingHours: {
    openTime: "09:00",
    closeTime: "19:00",
    workingDays: [1, 2, 3, 4, 5, 6],
    slotDurationMinutes: 30,
  },
};
